server:
  port: 9090

spring:
  application:
    name: Pdf

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/daishin?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.daishin.pdf.dto
#  configuration:
#    map-underscore-to-camel-case: true
    
storage:
  logPath: D:\DATA\log
  receivingPath: D:\DATA\receiving\
  completePath: D:\DATA\complete\

